<a href="https://colab.research.google.com/github/GabrielRamirezs/Metodos1_KarenQuevedo_GabrielRamirez/blob/main/Tarea4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#2
A = np.array([[3, -1, -1], [-1, 3, 1], [2, 1, 4]])
b = np.array([1, 3, 7])

x = np.zeros(len(b))
max_iterations = 25
tolerance = 1e-10

for k in range(max_iterations):
    x_new = np.copy(x)
    
    for i in range(len(b)):
        sum1 = np.dot(A[i, :i], x_new[:i])
        sum2 = np.dot(A[i, i + 1:], x[i + 1:])
        x_new[i] = (b[i] - sum1 - sum2) / A[i, i]

    if np.allclose(x, x_new, atol=tolerance, rtol=0.):
        break

    x = x_new

print(f'Solución después de {k+1} iteraciones:')
print(x)

In [3]:
#3
class SolucionSistemaLineal:
    def __init__(self, A, b):
        self.A = A
        self.b = b

    def jacobi(self, x0, itmax=1000, tolerancia=1e-16):
        x = x0.copy()
        n = len(self.b)
        
        for it in range(itmax):
            x_new = np.copy(x)
            
            for i in range(n):
                suma = 0.0
                for j in range(n):
                    if i != j:
                        suma += self.A[i, j] * x[j]
                x_new[i] = (self.b[i] - suma) / self.A[i, i]
            
            if np.linalg.norm(np.dot(self.A, x_new) - self.b) < tolerancia:
                break
            x = np.copy(x_new)
        
        print(f'Jacobi convergió en {it+1} iteraciones.')
        return x

    def gauss_seidel(self, x0, itmax=100, tolerancia=1e-16):
        x = x0.copy()
        n = len(self.b)
        
        for it in range(itmax):
            x_new = np.copy(x)
            
            for i in range(n):
                suma = 0.0
                for j in range(n):
                    if i != j:
                        suma += self.A[i, j] * x_new[j]
                x_new[i] = (self.b[i] - suma) / self.A[i, i]
            
            if np.linalg.norm(np.dot(self.A, x_new) - self.b) < tolerancia:
                break
            x = np.copy(x_new)
        
        print(f'Gauss-Seidel convergió en {it+1} iteraciones.')
        return x
    
A = np.array([[3,-1,-1],[-1,3,1],[2,1,4]])
b = np.array([1.,3.,7.])

x0 = np.array([0., 0., 0.])

solver = SolucionSistemaLineal(A, b)

x_jacobi = solver.jacobi(x0)
print('Solución con Jacobi:', x_jacobi)
x_gauss_seidel = solver.gauss_seidel(x0)
print('Solución con Gauss-Seidel:', x_gauss_seidel)


In [4]:
#4
import numpy as np

A = np.array([[1, 0, 0],
              [5, 1, 0],
              [-2, 3, 1]])

B = np.array([[4, -2, 1],
              [0, 3, 7],
              [0, 0, 2]])

def multiplicar_matrices(A, B):
    filas_A, columnas_A = A.shape
    filas_B, columnas_B = B.shape
    
    if columnas_A != filas_B:
        raise ValueError("Las matrices no se pueden multiplicar")

    resultado = np.zeros((filas_A, columnas_B))
 
    for i in range(filas_A):
        for j in range(columnas_B):
            for k in range(columnas_A):
                resultado[i, j] += A[i, k] * B[k, j]
    
    return resultado

AB = multiplicar_matrices(A, B)
print("Resultado de AB:")
print(AB)


In [8]:
#8
def lu_decomposition(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        L[i, i] = 1

    for j in range(n):
        for i in range(j+1):
            U[i, j] = A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))

        for i in range(j+1, n):
            L[i, j] = (A[i, j] - sum(L[i, k] * U[k, j] for k in range(j))) / U[j, j]

    return L, U

A = np.array([[4, -2, 1],
              [20, -7, 12],
              [-8, 13, 17]])

L_manual, U_manual = lu_decomposition(A)
L_manual, U_manual


(array([[ 1.,  0.,  0.],
        [ 5.,  1.,  0.],
        [-2.,  3.,  1.]]),
 array([[ 4., -2.,  1.],
        [ 0.,  3.,  7.],
        [ 0.,  0., -2.]]))

In [9]:
#10

def jacobi_method(A, tol=1e-10, max_iterations=100):
    def max_offdiag_symmetric(A):
        n = len(A)
        max_val = 0.0
        k = 0
        l = 0
        for i in range(n):
            for j in range(i+1, n):
                if abs(A[i, j]) > max_val:
                    max_val = abs(A[i, j])
                    k = i
                    l = j
        return k, l, max_val

    n = len(A)
    V = np.eye(n)
    iterations = 0
    while iterations < max_iterations:
        k, l, max_val = max_offdiag_symmetric(A)

        if max_val < tol:
            break

        if A[k, k] == A[l, l]:
            theta = np.pi / 4
        else:
            theta = 0.5 * np.arctan(2 * A[k, l] / (A[k, k] - A[l, l]))

        cos_t = np.cos(theta)
        sin_t = np.sin(theta)

        R = np.eye(n)
        R[k, k] = cos_t
        R[l, l] = cos_t
        R[k, l] = sin_t
        R[l, k] = -sin_t

        A = R.T @ A @ R
        V = V @ R
        iterations += 1

    eigenvalues = np.diag(A)
    eigenvectors = V
    return eigenvalues, eigenvectors


A = np.array([[4, 1, 1],
              [1, 3, 2],
              [1, 2, 5]])

eigenvalues_jacobi, eigenvectors_jacobi = jacobi_method(A)

eigenvalues_numpy, eigenvectors_numpy = np.linalg.eig(A)

eigenvalues_jacobi, eigenvectors_jacobi, eigenvalues_numpy, eigenvectors_numpy


(array([3.39688663, 2.57744745, 6.02566592]),
 array([[ 0.89796861,  0.03883191,  0.43834286],
        [-0.09286685,  0.99038792,  0.10250619],
        [-0.43014896, -0.13275486,  0.89294346]]),
 array([6.89510652, 3.39729507, 1.70759841]),
 array([[ 0.43170413,  0.88573564,  0.17059871],
        [ 0.49725362, -0.07589338, -0.86427949],
        [ 0.75257583, -0.45794385,  0.47319874]]))

In [10]:
#12
import numpy as np

def f1(x1, x2):
    return np.log(x1**2 + x2**2) - np.sin(x1 * x2) - np.log(2) - np.log(np.pi)

def f2(x1, x2):
    return np.exp(x1 - x2) + np.cos(x1 * x2)


def jacobian(x1, x2):
    df1_dx1 = (2 * x1 / (x1**2 + x2**2)) - (x2 * np.cos(x1 * x2))
    df1_dx2 = (2 * x2 / (x1**2 + x2**2)) - (x1 * np.cos(x1 * x2))
    df2_dx1 = np.exp(x1 - x2) - x2 * np.sin(x1 * x2)
    df2_dx2 = -np.exp(x1 - x2) - x1 * np.sin(x1 * x2)
    return np.array([[df1_dx1, df1_dx2],
                     [df2_dx1, df2_dx2]])

def newton_raphson(x0, tol=1e-10, max_iter=100):
    x = np.array(x0, dtype=float)
    for i in range(max_iter):
        f_val = np.array([f1(x[0], x[1]), f2(x[0], x[1])])
        J = jacobian(x[0], x[1])
        delta_x = np.linalg.solve(J, -f_val)
        x = x + delta_x
        if np.linalg.norm(delta_x) < tol:
            return x, i+1
    raise ValueError("Newton-Raphson did not converge")


x0 = [2, 2]


solution, iterations = newton_raphson(x0)

solution, iterations


(array([1.77245385, 1.77245385]), 7)

In [11]:
#12

def F1(x):
    x1, x2 = x
    f1 = np.log(x1**2 + x2**2) - np.sin(x1 * x2) - np.log(2 * np.pi)
    f2 = np.exp(x1 - x2) + np.cos(x1 * x2)
    return np.array([f1, f2])

def J1(x):
    x1, x2 = x
    df1_dx1 = 2 * x1 / (x1**2 + x2**2) - x2 * np.cos(x1 * x2)
    df1_dx2 = 2 * x2 / (x1**2 + x2**2) - x1 * np.cos(x1 * x2)
    df2_dx1 = np.exp(x1 - x2) - x2 * np.sin(x1 * x2)
    df2_dx2 = -np.exp(x1 - x2) - x1 * np.sin(x1 * x2)
    return np.array([[df1_dx1, df1_dx2], [df2_dx1, df2_dx2]])

def F2(x):
    x1, x2, x3 = x
    f1 = 6 * x1 - 2 * np.cos(x2 * x3) - 1
    f2 = 9 * x2 + np.sqrt(x1**2 + x2**2) + np.sin(x3) + 1.96
    f3 = 60 * x3 + 3 * np.exp(-x1 * x2) + 10 * np.pi - 3
    return np.array([f1, f2, f3])

def J2(x):
    x1, x2, x3 = x
    df1_dx1 = 6
    df1_dx2 = x3 * 2 * np.sin(x2 * x3)
    df1_dx3 = x2 * 2 * np.sin(x2 * x3)
    df2_dx1 = x1 / np.sqrt(x1**2 + x2**2)
    df2_dx2 = 9 + x2 / np.sqrt(x1**2 + x2**2)
    df2_dx3 = np.cos(x3)
    df3_dx1 = -3 * x2 * np.exp(-x1 * x2)
    df3_dx2 = -3 * x1 * np.exp(-x1 * x2)
    df3_dx3 = 60
    return np.array([[df1_dx1, df1_dx2, df1_dx3], [df2_dx1, df2_dx2, df2_dx3], [df3_dx1, df3_dx2, df3_dx3]])


def newton_raphson_no_scipy(F, J, x0, tol=1e-6, max_iter=100):
    x = np.array(x0, dtype=float)
    for i in range(max_iter):
        fx = F(x)
        if np.any(np.isnan(fx)) or np.any(np.isinf(fx)):
            print(f"No se puede continuar: el sistema generó valores indefinidos (NaN o Inf) en la iteración {i+1} con x = {x}")
            return None, i + 1
        if np.linalg.norm(fx, ord=2) < tol:
            return x, i + 1
        Jx = J(x)

        delta_x = np.linalg.solve(Jx, fx)
        x = x - delta_x
    return x, max_iter


x0_1 = [2, 2]
x0_2 = [0, 0, 0]
sol_1, iter_1 = newton_raphson_no_scipy(F1, J1, x0_1)
sol_2, iter_2 = newton_raphson_no_scipy(F2, J2, x0_2)

print(f"Solución sistema 1: {sol_1} en {iter_1} iteraciones")
print(f"Solución sistema 2: {sol_2} en {iter_2} iteraciones")



No se puede continuar: el sistema generó valores indefinidos (NaN o Inf) en la iteración 2 con x = [nan nan nan]
Solución sistema 1: [1.77245385 1.77245385] en 6 iteraciones
Solución sistema 2: None en 2 iteraciones


<ipython-input-11-a2e11fe39f8e>:29: RuntimeWarning: invalid value encountered in scalar divide
  df2_dx1 = x1 / np.sqrt(x1**2 + x2**2)
<ipython-input-11-a2e11fe39f8e>:30: RuntimeWarning: invalid value encountered in scalar divide
  df2_dx2 = 9 + x2 / np.sqrt(x1**2 + x2**2)


In [12]:
#13
import numpy as np

def jacobiano_cuarto_orden(f, x, h=0.01):
    n = len(x)
    m = len(f(x))
    J = np.zeros((m, n))


    for i in range(n):
        x_h = np.copy(x)
        f2h_plus = np.zeros(m)
        f1h_plus = np.zeros(m)
        f1h_minus = np.zeros(m)
        f2h_minus = np.zeros(m)


        x_h[i] = x[i] + 2*h
        f2h_plus = f(x_h)


        x_h[i] = x[i] + h
        f1h_plus = f(x_h)


        x_h[i] = x[i] - h
        f1h_minus = f(x_h)


        x_h[i] = x[i] - 2*h
        f2h_minus = f(x_h)


        J[:, i] = (-f2h_plus + 8*f1h_plus - 8*f1h_minus + f2h_minus) / (12*h)

    return J


def f(x):
    return np.array([x[0]**2 + x[1] + x[2]**3, np.sin(x[0]) + np.cos(x[1]*x[2])])


x = np.array([0.5, 0.5, 0.5])
h = 0.01

J_cuarto = jacobiano_cuarto_orden(f, x, h)
print("Jacobiano de cuarto orden:")
print(J_cuarto)


def jacobiano_segundo_orden(f, x, h=0.01):
    n = len(x)
    m = len(f(x))
    J = np.zeros((m, n))

    for i in range(n):
        x_h = np.copy(x)


        x_h[i] = x[i] + h
        f_plus = f(x_h)

        x_h[i] = x[i] - h
        f_minus = f(x_h)


        J[:, i] = (f_plus - f_minus) / (2*h)

    return J


J_segundo = jacobiano_segundo_orden(f, x, h)
print("Jacobiano de segundo orden:")
print(J_segundo)


errores = np.abs(J_cuarto - J_segundo)
print("Diferencias entre las aproximaciones de segundo y cuarto orden:")
print(errores)


Jacobiano de cuarto orden:
[[ 1.          1.          0.75      ]
 [ 0.87758256 -0.12370198 -0.12370198]]
Jacobiano de segundo orden:
[[ 1.          1.          0.7501    ]
 [ 0.87756794 -0.12370146 -0.12370146]]
Diferencias entre las aproximaciones de segundo y cuarto orden:
[[3.66373598e-15 3.77475828e-15 1.00000000e-04]
 [1.46260104e-05 5.15421700e-07 5.15421700e-07]]


In [13]:
#14
import sympy as sp


Jx = sp.Matrix([[0, 0, 0],
                [0, 0, -1],
                [0, 1, 0]])

Jy = sp.Matrix([[0, 0, 1],
                [0, 0, 0],
                [-1, 0, 0]])

Jz = sp.Matrix([[0, -1, 0],
                [1, 0, 0],
                [0, 0, 0]])


def commutator(A, B):
    return A * B - B * A


comm_Jx_Jy = commutator(Jx, Jy)
comm_Jy_Jz = commutator(Jy, Jz)
comm_Jz_Jx = commutator(Jz, Jx)

comm_Jx_Jy, comm_Jy_Jz, comm_Jz_Jx


(Matrix([
 [0, -1, 0],
 [1,  0, 0],
 [0,  0, 0]]),
 Matrix([
 [0, 0,  0],
 [0, 0, -1],
 [0, 1,  0]]),
 Matrix([
 [ 0, 0, 1],
 [ 0, 0, 0],
 [-1, 0, 0]]))