<a href="https://colab.research.google.com/github/GabrielRamirezs/Metodos1_KarenQuevedo_GabrielRamirez/blob/main/Tarea4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#2
A = np.array([[3, -1, -1], [-1, 3, 1], [2, 1, 4]])
b = np.array([1, 3, 7])

x = np.zeros(len(b))
max_iterations = 25
tolerance = 1e-10

for k in range(max_iterations):
    x_new = np.copy(x)

    for i in range(len(b)):
        sum1 = np.dot(A[i, :i], x_new[:i])
        sum2 = np.dot(A[i, i + 1:], x[i + 1:])
        x_new[i] = (b[i] - sum1 - sum2) / A[i, i]

    if np.allclose(x, x_new, atol=tolerance, rtol=0.):
        break

    x = x_new

print(f'Solución después de {k+1} iteraciones:')
print(x)

Solución después de 18 iteraciones:
[1. 1. 1.]


In [3]:
#3
class SolucionSistemaLineal:
    def __init__(self, A, b):
        self.A = A
        self.b = b

    def jacobi(self, x0, itmax=1000, tolerancia=1e-16):
        x = x0.copy()
        n = len(self.b)

        for it in range(itmax):
            x_new = np.copy(x)

            for i in range(n):
                suma = 0.0
                for j in range(n):
                    if i != j:
                        suma += self.A[i, j] * x[j]
                x_new[i] = (self.b[i] - suma) / self.A[i, i]

            if np.linalg.norm(np.dot(self.A, x_new) - self.b) < tolerancia:
                break
            x = np.copy(x_new)

        print(f'Jacobi convergió en {it+1} iteraciones.')
        return x

    def gauss_seidel(self, x0, itmax=100, tolerancia=1e-16):
        x = x0.copy()
        n = len(self.b)

        for it in range(itmax):
            x_new = np.copy(x)

            for i in range(n):
                suma = 0.0
                for j in range(n):
                    if i != j:
                        suma += self.A[i, j] * x_new[j]
                x_new[i] = (self.b[i] - suma) / self.A[i, i]

            if np.linalg.norm(np.dot(self.A, x_new) - self.b) < tolerancia:
                break
            x = np.copy(x_new)

        print(f'Gauss-Seidel convergió en {it+1} iteraciones.')
        return x

A = np.array([[3,-1,-1],[-1,3,1],[2,1,4]])
b = np.array([1.,3.,7.])

x0 = np.array([0., 0., 0.])

solver = SolucionSistemaLineal(A, b)

x_jacobi = solver.jacobi(x0)
print('Solución con Jacobi:', x_jacobi)
x_gauss_seidel = solver.gauss_seidel(x0)
print('Solución con Gauss-Seidel:', x_gauss_seidel)


Jacobi convergió en 35 iteraciones.
Solución con Jacobi: [1. 1. 1.]
Gauss-Seidel convergió en 26 iteraciones.
Solución con Gauss-Seidel: [1. 1. 1.]


In [4]:
#4
import numpy as np

A = np.array([[1, 0, 0],
              [5, 1, 0],
              [-2, 3, 1]])

B = np.array([[4, -2, 1],
              [0, 3, 7],
              [0, 0, 2]])

def multiplicar_matrices(A, B):
    filas_A, columnas_A = A.shape
    filas_B, columnas_B = B.shape

    if columnas_A != filas_B:
        raise ValueError("Las matrices no se pueden multiplicar")

    resultado = np.zeros((filas_A, columnas_B))

    for i in range(filas_A):
        for j in range(columnas_B):
            for k in range(columnas_A):
                resultado[i, j] += A[i, k] * B[k, j]

    return resultado

AB = multiplicar_matrices(A, B)
print("Resultado de AB:")
print(AB)


Resultado de AB:
[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]


In [5]:
#8
def lu_decomposition(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        L[i, i] = 1

    for j in range(n):
        for i in range(j+1):
            U[i, j] = A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))

        for i in range(j+1, n):
            L[i, j] = (A[i, j] - sum(L[i, k] * U[k, j] for k in range(j))) / U[j, j]

    return L, U

A = np.array([[4, -2, 1],
              [20, -7, 12],
              [-8, 13, 17]])

L_manual, U_manual = lu_decomposition(A)
L_manual, U_manual


(array([[ 1.,  0.,  0.],
        [ 5.,  1.,  0.],
        [-2.,  3.,  1.]]),
 array([[ 4., -2.,  1.],
        [ 0.,  3.,  7.],
        [ 0.,  0., -2.]]))

In [14]:
#10
def max_off_diagonal(A):
    n = len(A)
    max_val = 0
    p = 0
    q = 1
    for i in range(n):
        for j in range(i+1, n):
            if abs(A[i][j]) > max_val:
                max_val = abs(A[i][j])
                p = i
                q = j
    return p, q, max_val

def jacobi_rotate(A, p, q):
    if A[p][p] == A[q][q]:
        theta = 3.141592653589793 / 4
    else:
        theta = 0.5 * (2 * A[p][q] / (A[p][p] - A[q][q]))

    cos_theta = 1 / (1 + theta**2)**0.5
    sin_theta = theta / (1 + theta**2)**0.5


    n = len(A)
    A_new = [[A[i][j] for j in range(n)] for i in range(n)]

    for i in range(n):
        for j in range(n):
            if i == p or i == q or j == p or j == q:

                if i == p and j == p:
                    A_new[p][p] = cos_theta**2 * A[p][p] + 2 * cos_theta * sin_theta * A[p][q] + sin_theta**2 * A[q][q]
                elif i == q and j == q:
                    A_new[q][q] = sin_theta**2 * A[p][p] - 2 * cos_theta * sin_theta * A[p][q] + cos_theta**2 * A[q][q]
                elif (i == p and j == q) or (i == q and j == p):
                    A_new[p][q] = 0
                    A_new[q][p] = 0
                elif i == p:
                    A_new[i][j] = cos_theta * A[p][j] + sin_theta * A[q][j]
                elif i == q:
                    A_new[i][j] = -sin_theta * A[p][j] + cos_theta * A[q][j]
                elif j == p:
                    A_new[i][j] = cos_theta * A[i][p] + sin_theta * A[i][q]
                elif j == q:
                    A_new[i][j] = -sin_theta * A[i][p] + cos_theta * A[i][q]
    return A_new

def jacobi_eigenvalues(A, tol=1e-9, max_iterations=100):
    n = len(A)
    A_current = [row[:] for row in A]
    iterations = 0
    while iterations < max_iterations:
        p, q, max_val = max_off_diagonal(A_current)
        if max_val < tol:
            break
        A_current = jacobi_rotate(A_current, p, q)
        iterations += 1

    eigenvalues = [A_current[i][i] for i in range(n)]
    return eigenvalues


A = [[4, 1, 1],
     [1, 3, 2],
     [1, 2, 5]]

eigenvalues_jacobi = jacobi_eigenvalues(A)
print("Valores propios usando el método de Jacobi:", eigenvalues_jacobi)


import numpy as np
eigenvalues_numpy, _ = np.linalg.eig(A)
print("Valores propios usando np.linalg.eig:", eigenvalues_numpy)


Valores propios usando el método de Jacobi: [3.3333333333333335, 1.9999999999999996, 6.666666666666664]
Valores propios usando np.linalg.eig: [6.89510652 3.39729507 1.70759841]


In [16]:
#12


def f1(x1, x2):
    return np.log(x1**2 + x2**2) - np.sin(x1 * x2) - np.log(2) - np.log(np.pi)

def f2(x1, x2):
    return np.exp(x1 - x2) + np.cos(x1 * x2)


def jacobian(x1, x2):
    df1_dx1 = (2 * x1 / (x1**2 + x2**2)) - (x2 * np.cos(x1 * x2))
    df1_dx2 = (2 * x2 / (x1**2 + x2**2)) - (x1 * np.cos(x1 * x2))
    df2_dx1 = np.exp(x1 - x2) - x2 * np.sin(x1 * x2)
    df2_dx2 = -np.exp(x1 - x2) - x1 * np.sin(x1 * x2)
    return np.array([[df1_dx1, df1_dx2],
                     [df2_dx1, df2_dx2]])

def newton_raphson(x0, tol=1e-10, max_iter=100):
    x = np.array(x0, dtype=float)
    for i in range(max_iter):
        f_val = np.array([f1(x[0], x[1]), f2(x[0], x[1])])
        J = jacobian(x[0], x[1])
        delta_x = np.linalg.solve(J, -f_val)
        x = x + delta_x
        if np.linalg.norm(delta_x) < tol:
            return x, i+1
    raise ValueError("Newton-Raphson did not converge")


x0 = [2, 2]


solution, iterations = newton_raphson(x0)

solution, iterations
import numpy as np


def F1(x):
    f1 = np.log(x[0]**2 + x[1]**2) - np.sin(x[0] * x[1]) - np.log(2) - np.log(np.pi)
    f2 = np.exp(x[0] - x[1]) + np.cos(x[0] * x[1])
    return np.array([f1, f2])


def J1(x):
    j11 = (2 * x[0]) / (x[0]**2 + x[1]**2) - x[1] * np.cos(x[0] * x[1])
    j12 = (2 * x[1]) / (x[0]**2 + x[1]**2) - x[0] * np.cos(x[0] * x[1])
    j21 = np.exp(x[0] - x[1]) - x[1] * np.sin(x[0] * x[1])
    j22 = -np.exp(x[0] - x[1]) - x[0] * np.sin(x[0] * x[1])
    return np.array([[j11, j12], [j21, j22]])


def F2(x):
    f1 = 6*x[0] - 2 * np.cos(x[1] * x[2]) - 1
    f2 = 9*x[1] + np.sqrt(x[0]**2) + np.sin(x[2]) + 1.06 + 0.9
    f3 = 60*x[2] + 3 * np.exp(-x[0] * x[1]) + 10 * np.pi - 3
    return np.array([f1, f2, f3])


def J2(x):
    j11 = 6
    j12 = 2 * x[2] * np.sin(x[1] * x[2])
    j13 = 2 * x[1] * np.sin(x[1] * x[2])
    j21 = x[0] / np.sqrt(x[0]**2) if x[0] != 0 else 0
    j22 = 9
    j23 = np.cos(x[2])
    j31 = -3 * x[1] * np.exp(-x[0] * x[1])
    j32 = -3 * x[0] * np.exp(-x[0] * x[1])
    j33 = 60
    return np.array([[j11, j12, j13], [j21, j22, j23], [j31, j32, j33]])


def newton_raphson(F, J, x0, tol=1e-9, max_iter=100):
    x = np.array(x0, dtype=float)
    for i in range(max_iter):
        Fx = F(x)
        Jx = J(x)
        delta_x = np.linalg.solve(Jx, -Fx)
        x = x + delta_x
        if np.linalg.norm(delta_x) < tol:
            return x, i+1
    raise ValueError("El método de Newton-Raphson no convergió")

x0_1 = [2, 2]
solucion1, iteraciones1 = newton_raphson(F1, J1, x0_1)
print(f"Solución sistema 1: {solucion1}")
print(f"Iteraciones sistema 1: {iteraciones1}")


x0_2 = [0, 0, 0]
solucion2, iteraciones2 = newton_raphson(F2, J2, x0_2)
print(f"Solución sistema 2: {solucion2}")
print(f"Iteraciones sistema 2: {iteraciones2}")


Solución sistema 1: [1.77245385 1.77245385]
Iteraciones sistema 1: 6
Solución sistema 2: [ 0.49780395 -0.21698588 -0.52930208]
Iteraciones sistema 2: 4


In [9]:
#13
import numpy as np

def jacobiano_cuarto_orden(f, x, h=0.01):
    n = len(x)
    m = len(f(x))
    J = np.zeros((m, n))


    for i in range(n):
        x_h = np.copy(x)
        f2h_plus = np.zeros(m)
        f1h_plus = np.zeros(m)
        f1h_minus = np.zeros(m)
        f2h_minus = np.zeros(m)


        x_h[i] = x[i] + 2*h
        f2h_plus = f(x_h)


        x_h[i] = x[i] + h
        f1h_plus = f(x_h)


        x_h[i] = x[i] - h
        f1h_minus = f(x_h)


        x_h[i] = x[i] - 2*h
        f2h_minus = f(x_h)


        J[:, i] = (-f2h_plus + 8*f1h_plus - 8*f1h_minus + f2h_minus) / (12*h)

    return J


def f(x):
    return np.array([x[0]**2 + x[1] + x[2]**3, np.sin(x[0]) + np.cos(x[1]*x[2])])


x = np.array([0.5, 0.5, 0.5])
h = 0.01

J_cuarto = jacobiano_cuarto_orden(f, x, h)
print("Jacobiano de cuarto orden:")
print(J_cuarto)


def jacobiano_segundo_orden(f, x, h=0.01):
    n = len(x)
    m = len(f(x))
    J = np.zeros((m, n))

    for i in range(n):
        x_h = np.copy(x)


        x_h[i] = x[i] + h
        f_plus = f(x_h)

        x_h[i] = x[i] - h
        f_minus = f(x_h)


        J[:, i] = (f_plus - f_minus) / (2*h)

    return J


J_segundo = jacobiano_segundo_orden(f, x, h)
print("Jacobiano de segundo orden:")
print(J_segundo)


errores = np.abs(J_cuarto - J_segundo)
print("Diferencias entre las aproximaciones de segundo y cuarto orden:")
print(errores)


Jacobiano de cuarto orden:
[[ 1.          1.          0.75      ]
 [ 0.87758256 -0.12370198 -0.12370198]]
Jacobiano de segundo orden:
[[ 1.          1.          0.7501    ]
 [ 0.87756794 -0.12370146 -0.12370146]]
Diferencias entre las aproximaciones de segundo y cuarto orden:
[[3.66373598e-15 3.77475828e-15 1.00000000e-04]
 [1.46260104e-05 5.15421700e-07 5.15421700e-07]]


In [10]:
#14
import sympy as sp


Jx = sp.Matrix([[0, 0, 0],
                [0, 0, -1],
                [0, 1, 0]])

Jy = sp.Matrix([[0, 0, 1],
                [0, 0, 0],
                [-1, 0, 0]])

Jz = sp.Matrix([[0, -1, 0],
                [1, 0, 0],
                [0, 0, 0]])


def commutator(A, B):
    return A * B - B * A


comm_Jx_Jy = commutator(Jx, Jy)
comm_Jy_Jz = commutator(Jy, Jz)
comm_Jz_Jx = commutator(Jz, Jx)

comm_Jx_Jy, comm_Jy_Jz, comm_Jz_Jx


(Matrix([
 [0, -1, 0],
 [1,  0, 0],
 [0,  0, 0]]),
 Matrix([
 [0, 0,  0],
 [0, 0, -1],
 [0, 1,  0]]),
 Matrix([
 [ 0, 0, 1],
 [ 0, 0, 0],
 [-1, 0, 0]]))